# Generated by Django 3.2.14 on 2025-12-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_auto_20210225_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
