# Generated by Django 3.2.14 on 2025-12-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_subscription_last_viewed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="last_viewed_at",
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_viewed_action_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
