# Generated by Django 3.2.14 on 2025-12-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_auto_20251226_2000"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="last_viewed_action_id",
            new_name="last_viewed_bill_action_id",
        ),
    ]
