# Generated by Django 3.2.14 on 2025-12-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0006_rename_last_viewed_action_id_subscription_last_viewed_bill_action_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="last_viewed_bill_action_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
