networks:
  openstates-network:
      name: openstates-network

volumes:
  openstates-postgres:
    name: openstates-postgres

services:
  django:
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile
      args:
        UID: 1000
    restart: always
    environment:
      - UWSGI_ENABLE_THREADS=1
      - DEBUG=False
      - ALLOWED_HOSTS
      - SECRET_KEY
      - DEMO_PASSWORD
      - DATABASE_URL
      # - CACHE_URL
      # - EMAIL_HOST
      # - EMAIL_HOST_USER
      # - EMAIL_HOST_PASSWORD
      # - RECAPTCHA_PUBLIC_KEY
      # - RECAPTCHA_PRIVATE_KEY
    networks:
      - openstates-network
    logging:
      driver: "json-file"
      options:  
        max-size: "10m"
        max-file: "3"  # 30MB total

  nginx:
    build:
      context: docker/nginx
      args: 
        NGINX_CONF: nginx.prod.conf
    restart: always
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django
    networks:
      - openstates-network
    logging:
      driver: "json-file"
      options:  
        max-size: "10m"
        max-file: "3"

  db:
    profiles:
      - db
    restart: always  # remove when migrate to RDS
    image: "postgis/postgis:17-3.5-alpine"  # changed to match os-scrapers
    environment:
      POSTGRES_DB: openstatesorg
      POSTGRES_PASSWORD: openstates
      POSTGRES_USER: openstates
      POSTGRES_HOST_AUTH_METHOD: trust
    platform: linux/amd64 # Mac M1 compatibility
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openstates -d openstatesorg"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5405:5432
    volumes:
      - openstates-postgres:/var/lib/postgresql/data
    networks:
      - openstates-network
    logging:
      driver: "json-file"
      options:  
        max-size: "10m"
        max-file: "3" 

  # webpack:
  #   build: .
  #   command: ./docker/webpack-start.sh
  #   volumes:
  #     - .:/code
